# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20181005_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.Profile'),
            preserve_default=False,
        ),
    ]
