# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20181005_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='admirer',
        ),
        migrations.AddField(
            model_name='comment',
            name='imagecomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='images.Image'),
        ),
    ]
