# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_friendmgmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendmgmt',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendmgmt',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendMgmt',
        ),
    ]
